# -*- coding: utf-8 -*-
"""hw3 Sally Yin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1arIV017D3LCw6YlHWdIY7jz1nGiWyi_r
"""

import yfinance as yf
import pandas as pd

def YahooData2returns(YahooData):

    prices = YahooData['Close']
    pricevec = prices.values

    n = len(pricevec)
    returns = (pricevec[1:n] / pricevec[:n-1]) - 1

    return returns

def get_stock_data(symbol):
    data = yf.download(symbol)
    return data

data = get_stock_data('GS')
returns = YahooData2returns(data)

print("Returns:", returns)