# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168mg25jAhKJMuQsCsTCsMkPOT4HpTs_k
"""

def WhoAmI():
  return('xy2673')